apiVersion: v1
stringData:
  ID: "{{.eksaAccessKeyId}}"
  SECRET: "{{.eksaSecretAccessKey}}"
  REGION: {{.eksaRegion}}
kind: Secret
metadata:
  name: aws-secret
  namespace: eksa-packages
type: Opaque
