
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-anywhere-eks-amazonaws-com-v1alpha1-cluster
  failurePolicy: Fail
  name: mutation.cluster.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-anywhere-eks-amazonaws-com-v1alpha1-snowmachineconfig
  failurePolicy: Fail
  name: mutation.snowmachineconfig.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - snowmachineconfigs
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-anywhere-eks-amazonaws-com-v1alpha1-awsiamconfig
  failurePolicy: Fail
  name: validation.awsiamconfig.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsiamconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-anywhere-eks-amazonaws-com-v1alpha1-cloudstackdatacenterconfig
  failurePolicy: Fail
  name: validation.cloudstackdatacenterconfig.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudstackdatacenterconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-anywhere-eks-amazonaws-com-v1alpha1-cloudstackmachineconfig
  failurePolicy: Fail
  name: validation.cloudstackmachineconfig.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudstackmachineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-anywhere-eks-amazonaws-com-v1alpha1-cluster
  failurePolicy: Fail
  name: validation.cluster.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-anywhere-eks-amazonaws-com-v1alpha1-fluxconfig
  failurePolicy: Fail
  name: validation.fluxconfig.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fluxconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-anywhere-eks-amazonaws-com-v1alpha1-gitopsconfig
  failurePolicy: Fail
  name: validation.gitopsconfig.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gitopsconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-anywhere-eks-amazonaws-com-v1alpha1-oidcconfig
  failurePolicy: Fail
  name: validation.oidcconfig.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oidcconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-anywhere-eks-amazonaws-com-v1alpha1-snowmachineconfig
  failurePolicy: Fail
  name: validation.snowmachineconfig.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - snowmachineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-anywhere-eks-amazonaws-com-v1alpha1-vspheredatacenterconfig
  failurePolicy: Fail
  name: validation.vspheredatacenterconfig.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspheredatacenterconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-anywhere-eks-amazonaws-com-v1alpha1-vspheremachineconfig
  failurePolicy: Fail
  name: validation.vspheremachineconfig.anywhere.amazonaws.com
  rules:
  - apiGroups:
    - anywhere.eks.amazonaws.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vspheremachineconfigs
  sideEffects: None
