apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: {{.clusterName}}-md-0
  namespace: default
spec:
  clusterName: {{.clusterName}}
  replicas: {{.workerNodeReplicas}}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: {{.clusterName}}-md-0
      clusterName: {{.clusterName}}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachineTemplate
        name: {{.workloadTemplateName}}
      version: {{.kubernetesVersion}}
---
{{- if .needsNewWorkloadTemplate }}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: {{.workloadTemplateName}}
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: {{.clusterName}}-nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: default
      ami:
        id: {{.amiID}}
      rootVolume:
        size: 32
{{- end }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: {{.clusterName}}-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
          name: '{{"{{"}} ds.meta_data.local_hostname {{"}}"}}'