apiVersion: v1
kind: Secret
metadata:
  name: {{.clusterName}}-aws-iam-authenticator-ca
  namespace: {{.namespace}}
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
data:
  cert.pem: "{{.certPemBytes}}"
  key.pem: "{{.keyPemBytes}}"
type: Opaque