apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Release
metadata:
  creationTimestamp: null
spec:
  latestVersion: ""
  releases:
    - bundleManifestUrl: "embed:///config/bundle-release.yaml"
      date: ""
      eksABinary: {}
      gitCommit: ""
      gitTag: ""
      number: 0
      version: v0.0.0-dev
    - bundleManifestUrl: "embed:///config/bundle-release.yaml"
      date: ""
      eksABinary: {}
      gitCommit: ""
      gitTag: ""
      number: 0
      version: v0.0.0-custom
status: {}
