
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: tinkerbelldatacenterconfigs.anywhere.eks.amazonaws.com
spec:
  group: anywhere.eks.amazonaws.com
  names:
    kind: TinkerbellDatacenterConfig
    listKind: TinkerbellDatacenterConfigList
    plural: tinkerbelldatacenterconfigs
    singular: tinkerbelldatacenterconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TinkerbellDatacenterConfig is the Schema for the TinkerbellDatacenterConfigs
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TinkerbellDatacenterConfigSpec defines the desired state
              of TinkerbellDatacenterConfig
            properties:
              tinkerbellCertURL:
                type: string
              tinkerbellGRPCAuth:
                type: string
              tinkerbellHegelURL:
                type: string
              tinkerbellIP:
                description: 'Important: Run "make generate" to regenerate code after
                  modifying this file'
                type: string
              tinkerbellPBnJGRPCAuth:
                type: string
            required:
            - tinkerbellCertURL
            - tinkerbellGRPCAuth
            - tinkerbellHegelURL
            - tinkerbellIP
            - tinkerbellPBnJGRPCAuth
            type: object
          status:
            description: TinkerbellDatacenterConfigStatus defines the observed state
              of TinkerbellDatacenterConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
