
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: awsiamconfigs.anywhere.eks.amazonaws.com
spec:
  group: anywhere.eks.amazonaws.com
  names:
    kind: AWSIamConfig
    listKind: AWSIamConfigList
    plural: awsiamconfigs
    singular: awsiamconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AWSIamConfig is the Schema for the awsiamconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AWSIamConfigSpec defines the desired state of AWSIamConfig
            properties:
              awsRegion:
                description: AWSRegion defines a region in an AWS partition
                type: string
              backendMode:
                description: BackendMode defines multiple backends for aws-iam-authenticator
                  server The server searches for mappings in order
                items:
                  type: string
                type: array
              clusterID:
                description: ClusterID is a unique-per-cluster identifier for aws-iam-authenticator
                  server
                type: string
              mapRoles:
                description: MapRoles defines IAM role to a username and set of groups
                  mapping using EKSConfigMap BackendMode Each key must match AWS EKS
                  Style ConfigMap mapRoles
                type: string
              mapUsers:
                description: MapUsers defines IAM user to a username and set of groups
                  mapping using EKSConfigMap BackendMode Each key must match AWS EKS
                  Style ConfigMap mapUsers
                type: string
              partition:
                default: aws
                description: Partition defines the AWS partition on which the IAM
                  roles exist
                type: string
            type: object
          status:
            description: AWSIamConfigStatus defines the observed state of AWSIamConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
